### ISSUE TITLE
old_people = people.where(lambda p: p.age > 40) 

### ISSUE THREAD

**Issue by liavkoren** [avilum/linqit#3]
*sucks teeth*

Harsh.

**Comment by getconor** [comment]
The author might have meant this as a joke, but it really should be replaced. The current example would be inappropriate in any industry, and is especially inappropriate in information technology and software engineering where age discrimination is a **major** problem. I live and work in San Francisco where people *in their mid-twenties* have reported age discrimination and are already seeking cosmetic surgery to look younger. This example is a real turnoff.

**Comment by avilum** [comment]
I appriciate it, and obviously i meant it as a joke. Thanks for the attention.
