### ISSUE TITLE
Add support for order_by?

### ISSUE THREAD

**Issue by mikeckennedy** [avilum/linqit#7]
Hey, great library. I would love to do something like this but seems to just use the substandard built-in list implementation which returns None:

```python
people = List()
people.append(Person("Michael", 47))
people.append(Person("Sarah", 50))
people.append(Person("Jake", 42))

older = people.where(lambda p: p.age > 43).sort(lambda p: -p.age)
```

But sadly, sort returns None and I didn't see an `order_by`, what am I missing?

**Comment by avilum** [comment]
In progress - https://github.com/avilum/linqit/pull/8
